import type { ReadinessRecord } from "./pipeline";

export const sampleRecords: ReadinessRecord[] = [
  {
    customerId: "ACME-001",
    tradingName: "Acme Supply",
    legalName: "Acme Supply Limited",
    nzbn: "9429000000001",
    ppsrRegistrationNumber: "F000001",
    entityStatus: "active",
    ppsrDebtorMatches: true,
    exposureBand: "material",
    signerName: "Mia Director",
    signerRole: "Director",
    signerEmail: "mia.director@acme.example",
    authorityEvidence: "director-record",
    emailConfidence: "verified",
    templateVersion: "tc-v4",
    collateralClauseApproved: true,
    coverage: "future-and-existing",
    insolvencyRisk: "low",
    relatedParty: false,
    eSignEligible: true,
    customerResponse: "signed"
  },
  {
    customerId: "BOLT-014",
    tradingName: "Bolt Rentals",
    legalName: "Bolt Holdings Limited",
    nzbn: "9429000000014",
    ppsrRegistrationNumber: "F000014",
    entityStatus: "active",
    ppsrDebtorMatches: false,
    exposureBand: "high",
    signerName: "Noah Ops",
    signerRole: "Operations Manager",
    signerEmail: "noah.ops@bolt.example",
    authorityEvidence: "none",
    emailConfidence: "verified",
    templateVersion: "tc-v4",
    collateralClauseApproved: true,
    coverage: "future-and-existing",
    eSignEligible: true,
    customerResponse: "not-sent"
  },
  {
    customerId: "CEDAR-022",
    tradingName: "Cedar Workshop",
    legalName: "Cedar Workshop Limited",
    nzbn: "9429000000022",
    ppsrRegistrationNumber: "F000022",
    entityStatus: "active",
    ppsrDebtorMatches: true,
    exposureBand: "low",
    signerName: "Ivy Owner",
    signerRole: "Owner",
    signerEmail: "ivy@cedar.example",
    authorityEvidence: "account-owner-confirmed",
    emailConfidence: "verified",
    templateVersion: "tc-v4",
    collateralClauseApproved: true,
    coverage: "future-only",
    insolvencyRisk: "elevated",
    legacyBalanceNzd: 0,
    commerciallyWorthRemediating: false,
    restrictedPeriodIndicator: "unrelated",
    eSignEligible: true,
    customerResponse: "refused"
  },
  {
    customerId: "DELTA-037",
    tradingName: "Delta Freight",
    legalName: "Delta Freight Limited",
    nzbn: "9429000000037",
    ppsrRegistrationNumber: "F000037",
    entityStatus: "active",
    ppsrDebtorMatches: true,
    exposureBand: "material",
    signerName: "Ari CFO",
    signerRole: "Chief Financial Officer",
    signerEmail: "ari.cfo@delta.example",
    authorityEvidence: "delegated-authority",
    emailConfidence: "verified",
    templateVersion: "tc-v4-new-value-contemporaneous",
    collateralClauseApproved: true,
    coverage: "future-and-existing",
    insolvencyRisk: "elevated",
    legacyBalanceNzd: 28_000,
    willExtendNewCredit: true,
    newCreditLimitNzd: 60_000,
    commerciallyWorthRemediating: true,
    restrictedPeriodIndicator: "unrelated",
    eSignEligible: true,
    customerResponse: "negotiating"
  },
  {
    customerId: "ECHO-108",
    tradingName: "Echo Engineering",
    legalName: "Echo Engineering Limited",
    nzbn: "9429000000108",
    ppsrRegistrationNumber: "F000108",
    entityStatus: "active",
    ppsrDebtorMatches: true,
    exposureBand: "material",
    signerName: "Talia Finance",
    signerRole: "Finance Manager",
    signerEmail: "talia.finance@echo.example",
    authorityEvidence: "legal-approved",
    emailConfidence: "verified",
    templateVersion: "tc-v4",
    collateralClauseApproved: true,
    coverage: "counsel-review",
    eSignEligible: false,
    customerResponse: "wet-ink"
  },
  {
    customerId: "FERN-201",
    tradingName: "Fern Family Trust Trading",
    legalName: "Fern Family Trust",
    nzbn: "9429000000201",
    ppsrRegistrationNumber: "F000201",
    entityStatus: "active",
    ppsrDebtorMatches: true,
    debtorType: "trust",
    exposureBand: "material",
    signerName: "Paige Trustee",
    signerRole: "Trustee",
    signerEmail: "paige.trustee@fern.example",
    authorityEvidence: "delegated-authority",
    emailConfidence: "verified",
    templateVersion: "tc-v4",
    collateralClauseApproved: true,
    coverage: "future-and-existing",
    eSignEligible: true,
    customerResponse: "not-sent"
  },
  {
    customerId: "GULL-305",
    tradingName: "Gull Logistics",
    legalName: "Gull Logistics Limited",
    nzbn: "9429000000305",
    ppsrRegistrationNumber: "F000305",
    entityStatus: "active",
    ppsrDebtorMatches: true,
    exposureBand: "high",
    signerName: "Quinn Director",
    signerRole: "Director",
    signerEmail: "quinn.director@gull.example",
    authorityEvidence: "director-record",
    emailConfidence: "verified",
    templateVersion: "tc-v4",
    collateralClauseApproved: true,
    coverage: "existing-only",
    insolvencyRisk: "elevated",
    legacyBalanceNzd: 52_000,
    commerciallyWorthRemediating: true,
    restrictedPeriodIndicator: "unrelated",
    relatedParty: false,
    eSignEligible: true,
    customerResponse: "not-sent"
  },
  {
    customerId: "HARB-412",
    tradingName: "Harbour Marine",
    legalName: "Harbour Marine Limited",
    nzbn: "9429000000412",
    ppsrRegistrationNumber: "F000412",
    entityStatus: "active",
    ppsrDebtorMatches: true,
    exposureBand: "low",
    signerName: "Riley Owner",
    signerRole: "Owner",
    signerEmail: "riley.owner@harbour.example",
    authorityEvidence: "account-owner-confirmed",
    emailConfidence: "verified",
    templateVersion: "tc-v4",
    collateralClauseApproved: true,
    coverage: "future-only",
    annualContractValueNzd: 85_000,
    hasPersonalGuarantee: true,
    eSignEligible: true,
    customerResponse: "not-sent"
  },
  {
    customerId: "IRIS-501",
    tradingName: "Iris Components",
    legalName: "Iris Components Limited",
    nzbn: "9429000000501",
    ppsrRegistrationNumber: "F000501",
    entityStatus: "active",
    ppsrDebtorMatches: true,
    exposureBand: "material",
    signerName: "Sam Director",
    signerRole: "Director",
    signerEmail: "sam.director@iris.example",
    authorityEvidence: "director-record",
    emailConfidence: "verified",
    templateVersion: "tc-v4",
    collateralClauseApproved: true,
    coverage: "existing-only",
    insolvencyRisk: "elevated",
    legacyBalanceNzd: 95_000,
    relatedParty: true,
    restrictedPeriodIndicator: "related-party",
    eSignEligible: true,
    customerResponse: "not-sent"
  },
  {
    customerId: "JADE-602",
    tradingName: "Jade Retail",
    legalName: "Jade Retail Limited",
    nzbn: "9429000000602",
    ppsrRegistrationNumber: "F000602",
    entityStatus: "active",
    ppsrDebtorMatches: true,
    exposureBand: "high",
    signerName: "Tess Owner",
    signerRole: "Owner",
    signerEmail: "tess.owner@jade.example",
    authorityEvidence: "account-owner-confirmed",
    emailConfidence: "verified",
    templateVersion: "tc-v4",
    collateralClauseApproved: true,
    coverage: "existing-only",
    insolvencyRisk: "elevated",
    legacyBalanceNzd: 110_000,
    residualRiskApprovedBy: "commercial-owner-7",
    commerciallyWorthRemediating: true,
    restrictedPeriodIndicator: "unrelated",
    eSignEligible: true,
    customerResponse: "not-sent"
  }
];
