import type { ReadinessRecord } from "./pipeline";

export const sampleRecords: ReadinessRecord[] = [
  {
    customerId: "ACME-001",
    tradingName: "Acme Supply",
    legalName: "Acme Supply Limited",
    nzbn: "9429000000001",
    ppsrRegistrationNumber: "F000001",
    entityStatus: "active",
    ppsrDebtorMatches: true,
    exposureBand: "material",
    signerName: "Mia Director",
    signerRole: "Director",
    signerEmail: "mia.director@acme.example",
    authorityEvidence: "director-record",
    emailConfidence: "verified",
    templateVersion: "tc-v4",
    collateralClauseApproved: true,
    coverage: "future-and-existing",
    eSignEligible: true,
    customerResponse: "signed"
  },
  {
    customerId: "BOLT-014",
    tradingName: "Bolt Rentals",
    legalName: "Bolt Holdings Limited",
    nzbn: "9429000000014",
    ppsrRegistrationNumber: "F000014",
    entityStatus: "active",
    ppsrDebtorMatches: false,
    exposureBand: "high",
    signerName: "Noah Ops",
    signerRole: "Operations Manager",
    signerEmail: "noah.ops@bolt.example",
    authorityEvidence: "none",
    emailConfidence: "verified",
    templateVersion: "tc-v4",
    collateralClauseApproved: true,
    coverage: "future-and-existing",
    eSignEligible: true,
    customerResponse: "not-sent"
  },
  {
    customerId: "CEDAR-022",
    tradingName: "Cedar Workshop",
    legalName: "Cedar Workshop Limited",
    nzbn: "9429000000022",
    ppsrRegistrationNumber: "F000022",
    entityStatus: "active",
    ppsrDebtorMatches: true,
    exposureBand: "low",
    signerName: "Ivy Owner",
    signerRole: "Owner",
    signerEmail: "ivy@cedar.example",
    authorityEvidence: "account-owner-confirmed",
    emailConfidence: "verified",
    templateVersion: "tc-v4",
    collateralClauseApproved: true,
    coverage: "future-only",
    eSignEligible: true,
    customerResponse: "refused"
  },
  {
    customerId: "DELTA-037",
    tradingName: "Delta Freight",
    legalName: "Delta Freight Limited",
    nzbn: "9429000000037",
    ppsrRegistrationNumber: "F000037",
    entityStatus: "active",
    ppsrDebtorMatches: true,
    exposureBand: "material",
    signerName: "Ari CFO",
    signerRole: "Chief Financial Officer",
    signerEmail: "ari.cfo@delta.example",
    authorityEvidence: "delegated-authority",
    emailConfidence: "verified",
    templateVersion: "tc-v4",
    collateralClauseApproved: true,
    coverage: "future-and-existing",
    eSignEligible: true,
    customerResponse: "negotiating"
  },
  {
    customerId: "ECHO-108",
    tradingName: "Echo Engineering",
    legalName: "Echo Engineering Limited",
    nzbn: "9429000000108",
    ppsrRegistrationNumber: "F000108",
    entityStatus: "active",
    ppsrDebtorMatches: true,
    exposureBand: "material",
    signerName: "Talia Finance",
    signerRole: "Finance Manager",
    signerEmail: "talia.finance@echo.example",
    authorityEvidence: "legal-approved",
    emailConfidence: "verified",
    templateVersion: "tc-v4",
    collateralClauseApproved: true,
    coverage: "counsel-review",
    eSignEligible: false,
    customerResponse: "wet-ink"
  }
];
