import type { ReadinessRecord } from "./pipeline";

export const sampleRecords: ReadinessRecord[] = [
  {
    id: "ACME-001",
    tradingName: "Acme Supply",
    legalEntity: "Acme Supply Limited",
    nzbn: "9429000000001",
    entityStatus: "active",
    ppsrDebtorMatches: true,
    exposureBand: "material",
    proposedSignatory: "Mia Director",
    signatoryRole: "Director",
    authorityEvidence: "director-record",
    deliveryEmail: "mia.director@acme.example",
    emailConfidence: "verified",
    templateVersion: "tc-v4",
    collateralClauseApproved: true,
    coverage: "future-and-existing",
    eSignEligible: true,
    customerResponse: "signed"
  },
  {
    id: "BOLT-014",
    tradingName: "Bolt Rentals",
    legalEntity: "Bolt Holdings Limited",
    nzbn: "9429000000014",
    entityStatus: "active",
    ppsrDebtorMatches: false,
    exposureBand: "high",
    proposedSignatory: "Noah Ops",
    signatoryRole: "Operations Manager",
    authorityEvidence: "none",
    deliveryEmail: "noah.ops@bolt.example",
    emailConfidence: "verified",
    templateVersion: "tc-v4",
    collateralClauseApproved: true,
    coverage: "future-and-existing",
    eSignEligible: true,
    customerResponse: "not-sent"
  },
  {
    id: "CEDAR-022",
    tradingName: "Cedar Workshop",
    legalEntity: "Cedar Workshop Limited",
    nzbn: "9429000000022",
    entityStatus: "active",
    ppsrDebtorMatches: true,
    exposureBand: "low",
    proposedSignatory: "Ivy Owner",
    signatoryRole: "Owner",
    authorityEvidence: "account-owner-confirmed",
    deliveryEmail: "ivy@cedar.example",
    emailConfidence: "verified",
    templateVersion: "tc-v4",
    collateralClauseApproved: true,
    coverage: "future-only",
    eSignEligible: true,
    customerResponse: "refused"
  },
  {
    id: "DELTA-037",
    tradingName: "Delta Freight",
    legalEntity: "Delta Freight Limited",
    nzbn: "9429000000037",
    entityStatus: "active",
    ppsrDebtorMatches: true,
    exposureBand: "material",
    proposedSignatory: "Ari CFO",
    signatoryRole: "Chief Financial Officer",
    authorityEvidence: "delegated-authority",
    deliveryEmail: "ari.cfo@delta.example",
    emailConfidence: "verified",
    templateVersion: "tc-v4",
    collateralClauseApproved: true,
    coverage: "future-and-existing",
    eSignEligible: true,
    customerResponse: "negotiating"
  },
  {
    id: "ECHO-108",
    tradingName: "Echo Engineering",
    legalEntity: "Echo Engineering Limited",
    nzbn: "9429000000108",
    entityStatus: "active",
    ppsrDebtorMatches: true,
    exposureBand: "material",
    proposedSignatory: "Talia Finance",
    signatoryRole: "Finance Manager",
    authorityEvidence: "legal-approved",
    deliveryEmail: "talia.finance@echo.example",
    emailConfidence: "verified",
    templateVersion: "tc-v4",
    collateralClauseApproved: true,
    coverage: "counsel-review",
    eSignEligible: false,
    customerResponse: "wet-ink"
  }
];
